In [1]:
import pandas as pd
import statsmodels.api as sm
from statsmodels.discrete.count_model import ZeroInflatedPoisson

In [2]:
df=pd.read_csv("insurance2.csv")
df

      age  sex     bmi  children  smoker  region      charges  insuranceclaim
0      19    0  27.900         0       1       3  16884.92400               1
1      18    1  33.770         1       0       2   1725.55230               1
2      28    1  33.000         3       0       2   4449.46200               0
3      33    1  22.705         0       0       1  21984.47061               0
4      32    1  28.880         0       0       1   3866.85520               1
...   ...  ...     ...       ...     ...     ...          ...             ...
1333   50    1  30.970         3       0       1  10600.54830               0
1334   18    0  31.920         0       0       0   2205.98080               1
1335   18    0  36.850         0       0       2   1629.83350               1
1336   21    0  25.800         0       0       3   2007.94500               0
1337   61    0  29.070         0       1       1  29141.36030               1

[1338 rows x 8 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             1338 non-null   int64
 1   sex             1338 non-null   int64
 2   bmi             1338 non-null   float64
 3   children        1338 non-null   int64
 4   smoker          1338 non-null   int64
 5   region          1338 non-null   int64
 6   charges         1338 non-null   float64
 7   insuranceclaim  1338 non-null   int64
dtypes: float64(2), int64(6)
memory usage: 83.8 KB

In [4]:
df.isnull().sum()

age               0
sex               0
bmi               0
children          0
smoker            0
region            0
charges           0
insuranceclaim    0
dtype: int64

In [6]:
df=df[["age", "bmi", "charges", "insuranceclaim"]]
df

      age     bmi      charges  insuranceclaim
0      19  27.900  16884.92400               1
1      18  33.770   1725.55230               1
2      28  33.000   4449.46200               0
3      33  22.705  21984.47061               0
4      32  28.880   3866.85520               1
...   ...     ...          ...             ...
1333   50  30.970  10600.54830               0
1334   18  31.920   2205.98080               1
1335   18  36.850   1629.83350               1
1336   21  25.800   2007.94500               0
1337   61  29.070  29141.36030               1

[1338 rows x 4 columns]

In [7]:
df.isnull().sum()

age               0
bmi               0
charges           0
insuranceclaim    0
dtype: int64

In [9]:
X=df[["age", "bmi", "charges"]]
y=df["insuranceclaim"]

In [10]:
X=sm.add_constant(X)
X.head()

   const  age     bmi      charges
0    1.0   19  27.900  16884.92400
1    1.0   18  33.770   1725.55230
2    1.0   28  33.000   4449.46200
3    1.0   33  22.705  21984.47061
4    1.0   32  28.880   3866.85520

In [12]:
model=ZeroInflatedPoisson(endog=y, exog=X, exog_infl=X)

In [13]:
result=model.fit(maxiter=200, method="bfgs")

         Current function value: 21.735326
         Iterations: 0
         Function evaluations: 13
         Gradient evaluations: 2

C:\Users\tamil\anaconda3\Lib\site-packages\statsmodels\discrete\discrete_model.py:2385: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
C:\Users\tamil\anaconda3\Lib\site-packages\statsmodels\discrete\discrete_model.py:1331: RuntimeWarning: overflow encountered in exp
  return -np.exp(XB) +  endog*XB - gammaln(endog+1)
C:\Users\tamil\anaconda3\Lib\site-packages\statsmodels\discrete\discrete_model.py:1508: RuntimeWarning: overflow encountered in exp
  L = np.exp(np.dot(X,params) + offset + exposure)
C:\Users\tamil\anaconda3\Lib\site-packages\statsmodels\discrete\discrete_model.py:1509: RuntimeWarning: overflow encountered in multiply
  return (self.endog - L)[:,None] * X
C:\Users\tamil\anaconda3\Lib\site-packages\statsmodels\discrete\discrete_model.py:1074: RuntimeWarning: overflow encountered in exp
  return np.exp(linpred)
C:\Users\tamil\anaconda3\Lib\site-packages\statsmodels\discrete\discrete_model.py:2385: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
C:\Users\tamil\anaconda3\Lib\site-packages\statsmodels\discrete\discrete_model.py:1331: RuntimeWarning: overflow encountered in exp
  return -np.exp(XB) +  endog*XB - gammaln(endog+1)
C:\Users\tamil\anaconda3\Lib\site-packages\scipy\optimize\_optimize.py:1313: OptimizeWarning: Desired error not necessarily achieved due to precision loss.
  res = _minimize_bfgs(f, x0, args, fprime, callback=callback, **opts)
C:\Users\tamil\anaconda3\Lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

In [14]:
print(result.summary())

                     ZeroInflatedPoisson Regression Results
===============================================================================
Dep. Variable:          insuranceclaim   No. Observations:                 1338
Model:             ZeroInflatedPoisson   Df Residuals:                     1334
Method:                            MLE   Df Model:                            3
Date:                 Thu, 02 Jul 2026   Pseudo R-squ.:                  -23.18
Time:                         10:59:43   Log-Likelihood:                -29082.
converged:                       False   LL-Null:                       -1202.5
Covariance Type:             nonrobust   LLR p-value:                     1.000
===================================================================================
                      coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
inflate_const       0.1000   1.23e+07   8.15e-09      1.000    -2.4e+07     2.4e+07
inflate_age         0.1000   1.51e+05    6.6e-07      1.000   -2.97e+05    2.97e+05
inflate_bmi         0.1000   3.56e+05   2.81e-07      1.000   -6.97e+05    6.97e+05
inflate_charges     0.1000    168.394      0.001      1.000    -329.945     330.145
const              -0.7810      0.280     -2.790      0.005      -1.330      -0.232
age                 0.0011      0.003      0.346      0.729      -0.005       0.007
bmi                 0.0014      0.008      0.176      0.860      -0.014       0.017
charges           1.65e-05    2.9e-06      5.695      0.000    1.08e-05    2.22e-05
===================================================================================

In [15]:
print(df["insuranceclaim"].value_counts())

insuranceclaim
1    783
0    555
Name: count, dtype: int64

In [16]:
zero_percentage=((df["insuranceclaim"]==0).mean())*100
print("Zero Percentage:", round(zero_percentage,2),"%")

Zero Percentage: 41.48 %

In [18]:
age = int(input("Enter Age: "))
bmi = float(input("Enter BMI: "))
charges = float(input("Enter Charges: "))

Enter Age:  20
Enter BMI:  45
Enter Charges:  50000

In [20]:
new_data = pd.DataFrame({"const":[1],"age":[age],"bmi":[bmi],"charges":[charges]})

In [21]:
prediction = result.predict(exog=new_data,exog_infl=new_data)
print("Predicted Insurance Claim:",round(prediction[0]))

Predicted Insurance Claim: 0